[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "chromium",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "dbus",
  "drm",
  "expat",
  "fontconfig",
  "freetype",
  "glib",
  "gtk3",
  "pango",
  "cairo",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libxkbcommon",
  "alsa-lib"
]

[start]
cmd = "python main.py"
